lo_commande_homepage:
    path:     /
    defaults: { _controller: LOTicketBundle:Home:index }

lo_commande_form:
    path:     /commande
    defaults: { _controller: LOTicketBundle:Commande:add }

lo_ticket_form:
    path:     /ticket
    defaults: { _controller: LOTicketBundle:Ticket:add }

lo_commande_panier:
    path:     /panier
    defaults: { _controller: LOTicketBundle:Commande:panier }

lo_commande_recapitulatif:
    path:     /recapitulatif
    defaults: { _controller: LOTicketBundle:Commande:recapitulatif }

lo_commande_renvoi:
    path:     /renvoi
    defaults: { _controller: LOTicketBundle:Commande:renvoi }
