lo_commande_homepage:
    path:     /
    defaults: { _controller: LOTicketBundle:commande:index }

lo_commande_form:
    path:     /commande
    defaults: { _controller: LOTicketBundle:commande:add }