lo_commande_homepage:
    path:     /
    defaults: { _controller: LOTicketBundle:Home:index }
    schemes:  [https]
lo_commande_form:
    path:     /commande
    defaults: { _controller: LOTicketBundle:Commande:add }
    schemes:  [https]
lo_ticket_form:
    path:     /ticket
    defaults: { _controller: LOTicketBundle:Ticket:add }
    schemes:  [https]
lo_commande_panier:
    path:     /panier
    defaults: { _controller: LOTicketBundle:Commande:panier }
    schemes:  [https]
lo_commande_recapitulatif:
    path:     /recapitulatif
    defaults: { _controller: LOTicketBundle:Commande:recapitulatif }
    schemes:  [https]
lo_commande_renvoi:
    path:     /renvoi
    defaults: { _controller: LOTicketBundle:Commande:renvoi }
    schemes:  [https]