lo_commande_homepage:
    path:     /
    defaults: { _controller: LOTicketBundle:Commande:index }

lo_commande_form:
    path:     /commande
    defaults: { _controller: LOTicketBundle:Commande:add }

lo_ticket_form:
    path:     /ticket
    defaults: { _controller: LOTicketBundle:Ticket:add }

lo_commande_panier:
    path:     /commande/panier
    defaults: { _controller: LOTicketBundle:Commande:panier }

lo_commande_recapitulatif:
    path:     /commande/recapitulatif
    defaults: { _controller: LOTicketBundle:Commande:recapitulatif }