services:
#    lo_ticket.example:
#        class: LO\TicketBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    app.send_mail:
        class:  LO\TicketBundle\Services\Mailer\SendMail
        public: true
        arguments:
            $twig: '@twig'
            $mailer: '@mailer'