lo_ticket_ticket:
    resource: "@LOTicketBundle/Controller/TicketController.php"
    type:     annotation

lo_ticket:
    resource: "@LOTicketBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
