crud_ticket_index:
    path:     /
    defaults: { _controller: "LOTicketBundle:Ticket:index" }
    methods:  GET

crud_ticket_show:
    path:     /{id}/show
    defaults: { _controller: "LOTicketBundle:Ticket:show" }
    methods:  GET



